apiVersion: v1
kind: Service
metadata:
  name: devops-monitoring-portal-service
  labels:
    app: devops-monitoring-portal
spec:
  type: NodePort
  selector:
    app: devops-monitoring-portal
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
